DROP TABLE VEHICLE;
CREATE TABLE IF NOT EXISTS VEHICLE
(
    VEHICLE_NO VARCHAR(10) NOT NULL PRIMARY KEY,
    COLOR      VARCHAR(10),
    WHEEL      INT,
    SEAT       INT
);

INSERT INTO VEHICLE (VEHICLE_NO, COLOR, WHEEL, SEAT) VALUES ('TEM0443', 'Red', 2, 2);
INSERT INTO VEHICLE (VEHICLE_NO, COLOR, WHEEL, SEAT) VALUES ('TEM0442', 'blue', 2, 2);